import { SessionProvider } from "@/utils/SessionProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "@/components/Provider";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "wildlife-conservation",
  description: "Generated by create next app",
  icons: {
    icon: "/public/favicon.ico",
    shortcut: "/public/favicon.ico",
    apple: "/public/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <SessionProvider>
            <link rel="icon" href="/public/favicon.ico" sizes="any" />
            <Providers>
                {children}
            </Providers>
          </SessionProvider>
      </body>
    </html>
  );
}
